Add back support for unencoded folder/workspace query params
cdr/vscode pull request #15
Opened 2021-11-10 22:46 UTC by code-asher

Fixes cdr/code-server#4484.

2021-11-10 23:31 UTC, jsjoeio approved these changes
LGTM! Left a couple comments but all none-blocking

2021-11-10 23:31 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> + * @remark coder
❓/nit: is `@remark` is an official JSDoc tag? Not finding it in the [index](https://jsdoc.app/)

I wonder if [`@author`](https://jsdoc.app/tags-author.html) is better.

2021-11-10 23:31 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
Nice comment 👏

2021-11-10 23:31 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> +			return "vscode-remote://" + value;
nit: modernize 😛
```suggestion
			return `vscode-remote://${value};
```

2021-11-10 23:31 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> +				value = toRemote(value); // NOTE@coder: See above.
👏 appreciate the thoroughness of your comments with these inline notes 👏

2021-11-10 23:31 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> +			targetHref = `${document.location.origin}${document.location.pathname}?${WorkspaceProvider.QUERY_PARAM_WORKSPACE}=${target}`;
🤔 Just thinking out loud to make sure I understand this change. In these two `if` blocks, we're modifying the `targetHref` based on the `workspace.folderUri.scheme`. If the scheme matches the `vscodeRemote` (which I'm guessing would be `localhost` with code-server?), then we use our `encodePath` helper function which maintains the `/` in the URI/URL so that it's easier for users to edit these by hand.

Is that right?

2021-11-11 22:31 UTC, TeffenEllis commented on src/vs/code/browser/workbench/workbench.ts
> +			return "vscode-remote://" + value;
Something like?
```ts
import { URI } from 'vs/base/common/uri';
import { Schemas } from 'vs/base/common/network';

return URI.from({ 
  scheme: Schemas.vscodeRemote, 
  authority: '/foo/bar/baz’ 
}).toString(true /* skip encoding */)

// => vscode-remote:///foo/bar/baz
```

2021-11-11 22:50 UTC, TeffenEllis requested changes

2021-11-11 22:50 UTC, TeffenEllis commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
```suggestion
		/** @coder Modified to print as a human-readable string for file paths. */
```

2021-11-11 22:50 UTC, TeffenEllis commented on src/vs/code/browser/workbench/workbench.ts
> +			targetHref = `${document.location.origin}${document.location.pathname}?${WorkspaceProvider.QUERY_PARAM_FOLDER}=${target}`;
Can this interpolation be replaced with a URL constructor? Something like:

```ts
const url = new URL(window.location.pathname, window.location.origin);

url.searchParams.set(
  WorkspaceProvider.QUERY_PARAM_FOLDER,
   workspace.folderUri.scheme === Schemas.vscodeRemote
     ? encodePath(workspace.folderUri.path)
     : encodeURIComponent(workspace.folderUri.toString()));
```

2021-11-11 22:50 UTC, TeffenEllis commented on src/vs/code/browser/workbench/workbench.ts
> +};
nit
```suggestion
export const encodeURIComponentHumanReadable = (path: string): string => {
       // Encode everything...
       return encodeURIComponent(path)
         // Decode forward slashes to retain a human-readable result 
	  .replaceAll(encodeURIComponent('/'), '/')
```

2021-11-12 16:06 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> + * @remark coder
Ooo, `@author` sounds great.

2021-11-12 16:07 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
I can standardize on that if we want.  I lean toward TODO, NOTE, etc because my editor highlights it so it stands out.

2021-11-12 16:12 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +};
What is the advantage to doing it this way?

2021-11-12 16:16 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +			targetHref = `${document.location.origin}${document.location.pathname}?${WorkspaceProvider.QUERY_PARAM_FOLDER}=${target}`;
This looks like it would work but I wanted to avoid modifying the original logic as much as possible.

2021-11-12 16:30 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +			return "vscode-remote://" + value;
Ahh template strings, I like to avoid them if there is just one variable at the start or end hahaha, I guess my old-school brain finds it more readable.

Good call on `Schemas.vscodeRemote`.  I completely forgot to replace the hard-coded string with that.

The change feels semantically odd, right?  Since what we have is a path and not an authority.  I messed around with adding it to the path but it seems to lose the double slash.  It does get passed into `URI.parse` so we should still get all the same validation that way.

2021-11-12 16:33 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +			targetHref = `${document.location.origin}${document.location.pathname}?${WorkspaceProvider.QUERY_PARAM_WORKSPACE}=${target}`;
`vscodeRemote` is `vscode-remote`.  It is the scheme portion (`file`, `http`, `https`, etc).

In VS Code the `vscode-remote` scheme means the same thing as `file`, meaning it is on disk but on the remote side.

Yup, you got it right!

2021-11-12 16:35 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
Maybe I need to add highlight for jsdoc tags.

2021-11-12 16:43 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
nvm I do but my editor is not recognizing `@coder` as a valid tag name.

2021-11-12 16:45 UTC, code-asher commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
Maybe I can do multi-line and use `@author coder`.

2021-11-12 16:58 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> +			targetHref = `${document.location.origin}${document.location.pathname}?${WorkspaceProvider.QUERY_PARAM_WORKSPACE}=${target}`;
Ahh just means it's on the remote side, got it. Thank you!

2021-11-12 17:04 UTC, jsjoeio commented on src/vs/code/browser/workbench/workbench.ts
> +		// NOTE@coder: Modified to print as a human-readable string for file paths.
I'm down for `@author` and also standardizing!

2021-11-18 15:47 UTC, TeffenEllis approved these changes

2021-11-18 15:48 UTC, merged